import Header from '@/components/header/Header'
import './globals.css'
import type { Metadata } from 'next'
import Developed from '@/components/Form/Developed'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Developed/>
        </body>
    </html>
  )
}
